
// Images ...


export const male = "/images/male.svg"
export const female = "/images/female.svg"

export const realintakeslogo = "/images/realintakelogo.png"
export const playstoreimage = "/images/playstorenew.png"
export const appstoreimage = "/images/appstore.png"
export const armswithdumbels = "/images/armswithdumbels.png"
export const diet = "/images/diet.png"
export const dietitems = "/images/dietitems.png"
export const dumbels = "/images/dumbels.png"
export const intakenavigation = "/images/intakenavigation.png"
export const proteinintakes = "/images/proteinintakes.png"
export const rightintakemobileimage = "/images/rightintakemobileimage.png"
export const rightintakemobilemeals = "/images/rightintakemobilemeals.png"
export const workoutplan = "/images/workoutplan.png"
export const hammerimage = "/images/hammer.png"
export const analysis = "/images/analysis.png"
export const cheatmeal1 = "/images/cheatmeal1.png"
export const cheatmeal2 = "/images/cheatmeal2.png"
export const cheatmeal3 = "/images/cheatmeal3.png"
export const gymworkout = "/images/gymworkout.png"
export const realintakegrp = "/images/realintakegrp.png"
export const realintakenut = "/images/realintakenut.png"
export const aifitness = "/images/aifitness.png"
export const fitnessbackground = "/images/fitnessbackground2.png"
export const previcon = "/images/previcon.svg"
export const rightarrow = "/images/rightarrow.svg"
export const bmiimage = "/images/bmiimage.svg"
export const fitnessimg1 = "/images/fitnessimg1.svg"
export const fitnessimg2 = "/images/fitnessimg2.svg"
export const goalbody1 = "/images/goalbody1.svg"
export const goalbody2 = "/images/goalbody2.svg"
export const goalbody3 = "/images/goalbody3.svg"
export const workoutimg1 = "/images/workoutimg1.svg"
export const workoutimg2 = "/images/workoutimg2.svg"
export const workoutimg3 = "/images/workoutimg3.svg"
export const workoutinsight = "/images/workoutinsight.svg"
export const bodyfat1 = "/images/bodyfat1.svg"
export const bodyfat2 = "/images/bodyfat2.svg"
export const bodyfat3 = "/images/bodyfat3.svg"
export const bodyfat4 = "/images/bodyfat4.svg"
export const bodyfat5 = "/images/bodyfat5.svg"
export const bodyfat6 = "/images/bodyfat6.svg"
export const bodyfat7 = "/images/bodyfat7.svg"
export const bodyfat8 = "/images/bodyfat8.svg"
export const acheivmenticon = "/images/acheivmenticon.svg"
export const congratsicon = "/images/congratsicon.svg"
export const cheatmealimage = "/images/cheatmealimage.svg"
export const transitionarrow = "/images/transitionarrow.svg"
export const caloriesicon = "/images/caloriesicon.svg"
export const waterglassicon = "/images/waterglass.svg"
export const summaryicon1 = "/images/summaryicon1.svg"
export const summaryicon2 = "/images/summaryicon2.svg"
export const summaryicon3 = "/images/summaryicon3.svg"
export const summaryicon4 = "/images/summaryicon4.svg"
export const summaryicon5 = "/images/summaryicon5.svg"
export const offerbackground = "/images/offerbackground.svg"

//emojis
export const cryemoji = "/images/emojis/cry.svg"
export const fireemoji = "/images/emojis/fire.svg"
export const shockemoji = "/images/emojis/shock.svg"
export const crownemoji = "/images/emojis/crown.svg"

export const batemoji = "/images/emojis/bat.svg"
export const humanemoji = "/images/emojis/human.svg"
export const catemoji = "/images/emojis/cat.svg"
export const sunemoji = "/images/emojis/sun.svg"

export const waterglassemoji = "/images/emojis/waterGlass.svg"
export const wavemoji = "/images/emojis/wave.svg"

export const bodyfatshadow1 = "/images/bodyfatshadow1.png"
export const bodyfatshadow2 = "/images/bodyfatshadow2.png"

